name: user_management_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  # State Management
  flutter_bloc:
  equatable:

  # Persistencia
  hive:
  hive_flutter:

  # Inyección de dependencias
  get_it:

  # Navegación
  go_router:

  # Utilidades
  intl:
  dartz:
  json_annotation:
  uuid: 
  phone_form_field:
  phone_numbers_parser:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  mocktail:
  bloc_test:
  build_runner:
  hive_generator:
  json_serializable:
  hive_test: 

flutter:
  uses-material-design: true

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700
